server {
    listen 80;
    listen [::]:80;
    server_name worldmonitor.yueyanc.cn;

    location ^~ /.well-known/acme-challenge {
        allow all;
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name worldmonitor.yueyanc.cn;
    http2 on;

    ssl_certificate /www/sites/s2a.yueyanc/ssl/fullchain.pem;
    ssl_certificate_key /www/sites/s2a.yueyanc/ssl/privkey.pem;
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    client_max_body_size 32M;

    location / {
        proxy_pass http://127.0.0.1:3480;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_read_timeout 180s;
        proxy_send_timeout 180s;
    }
}
